name: Run Autify Test

on:
  workflow_dispatch:

jobs:
  run-autify:
    runs-on: ubuntu-latest
    steps:
      - name: Install Autify CLI
        run: npm install -g @autify/cli

      - name: Authenticate Autify
        run: autify login --token ${{ secrets.AUTIFY_API_KEY }}

      - name: Run test
        run: autify web tests run --scenario-id=369393
