name: Run Autify Test

on:
  push:
    branches: [main]

jobs:
  run-autify:
    runs-on: ubuntu-latest
    steps:
      - name: Run Autify Test Plan
        env:
          AUTIFY_API_KEY: ${{ secrets.AUTIFY_API_KEY }}
          TEST_PLAN_ID: "your-test-plan-id"
        run: |
          echo "Triggering Autify test plan..."
          curl -X POST "https://app.autify.com/api/v1/test_plans/${TEST_PLAN_ID}/run" \
            -H "Authorization: Bearer $AUTIFY_API_KEY"
