name: Run Autify Test

on:
  workflow_dispatch:

jobs:
  run-autify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Autify CLI
        uses: autifyhq/actions-setup-cli@v2

      - name: Run Autify Scenario
        env:
          AUTIFY_WEB_ACCESS_TOKEN: ${{ secrets.AUTIFY_WEB_ACCESS_TOKEN }}
        run: autify web test run https://app.autify.com/projects/14749/test_plans/953090

