name: Run Autify Test

on:
  workflow_dispatch:

jobs:
  run-autify:
    runs-on: ubuntu-latest
    steps:
      - name: Run Autify Test Plan
        env:
          AUTIFY_API_KEY: ${{ secrets.AUTIFY_API_KEY }}
          TEST_PLAN_ID: "953090"
        run: |
          echo "Triggering Autify test plan..."
          curl -X POST "https://app.autify.com/api/v1/test_plans/${TEST_PLAN_ID}/runs" \
            -H "Authorization: Bearer $AUTIFY_API_KEY"
