# .github/workflows/trigger-auto.yml
name: Trigger Auto Repo Workflow

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn

jobs:
  trigger:
    runs-on: windows-latest  # ✅ Sửa "window-latest" thành "windows-latest"
    steps:
        - name: Trigger repo-auto workflow
          shell: pwsh
          run: |
            $json = '{"event_type":"trigger-from-repo-source"}'
            curl -X POST `
              -H "Authorization: token ${{ secrets.PAT_TRIG }}" `
              -H "Accept: application/vnd.github+json" `
              -H "Content-Type: application/json" `
              https://api.github.com/repos/AnhAutomationTester/SeleniumBDDFramework/dispatches `
              -d $json
