# .github/workflows/trigger-auto.yml
name: Trigger Auto Repo Workflow

on:
  push:
    branches:
      - main  # hoặc nhánh bạn muốn

jobs:
  trigger:
    runs-on: windows-latest  # ✅ Sửa "window-latest" thành "windows-latest"
    steps:
      - name: Trigger repo-auto workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT_TRIGGER }}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/AnhAutomationTester/SeleniumBDDFramework/dispatches -d "{\"event_type\":\"trigger-from-repo-source\"}"

