name: Run Autify Test

on:
  workflow_dispatch:

jobs:
  run-autify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Autify CLI
        uses: autifyhq/actions-setup-cli@v2

      - name: Authenticate Autify
        run: autify login --token ${{ secrets.AUTIFY_API_KEY }}

      - name: Run Autify Scenario
        run: autify web tests run --scenario-id=369393

